import csv
from datetime import datetime
import matplotlib.pyplot as plt

filename= "data/fileTouches_rootbeer.csv"                                           # CSV can be changed, but it was generated by codyn_authorFileTouches.py
with open(filename, mode='r')as file:
    csvFile = csv.reader(file, delimiter=';')
    next(csvFile, None)
    
    for lines in csvFile:                                                           # Each line is a different author with their commits
        x=[]                                                                        # Files    
        y=[]                                                                        # Weeks From Today
        line = lines[1]                                                             # File Changed,Date
     
        l = line.replace('[','')                                                    # Removes extra chars for cleanup
        l = l.replace(']','')
        l = l.replace('\'','')
     
        li = list(l.split(", "))                                                    # Put data into a list
  
        for i in range(len(li)):                                                    # Goes through each element in the list
            if (i % 2):                                                             # List structure: file,date,file,date,file,date
                li[i] = datetime.strptime(li[i], '%Y-%m-%dT%H:%M:%SZ').date()       # Formats date from list to datetime object
                weeksFromToday = (datetime.now().date() - li[i]).days / 7           # Weeks form today
                y.append(weeksFromToday)                                            # Append to y
            else:                                                                   
                file = li[i].rsplit("/",1)                                          # Grabs last part of directory (filename.java)
                x.append(file[1])                                                   # Append to x
        
        plt.scatter(x,y)                                                            # Plots author's commits

plt.xticks(rotation=45)                                                             # Changes orientation of x axis
plt.tick_params(labelsize=6)                                                        # Changes size of labels
plt.xlabel('Files')                                                                 # X Axis Label
plt.ylabel('Weeks from Today')                                                      # Y Axis Label
plt.gca().invert_yaxis()                                                            # Inverts Y Axis to better display plot
plt.show()                                                                          # Displays plots from all authors